openapi: '3.1.0'
info:
  title: User API
  version: 1.0.0
servers:
  - url: https://events-au-v2.vercel.app/users
    description: Example service deployment.
paths:
  /users:
    get:
      operationId: getUsers
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier for the user.
        fId:
          type: string
          description: The Firebase ID associated with the user.
        firstName:
          type: string
          description: The first name of the user.
        lastName:
          type: string
          description: The last name of the user (optional).
        email:
          type: string
          format: email
          description: The email address of the user.
        phone:
          type: integer
          description: The phone number of the user.
        createdAt:
          type: string
          format: date-time
          description: The date and time when the user was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time when the user was last updated.
        __v:
          type: integer
          description: Version indicator (optional).
      required:
        - _id
        - fId
        - firstName
        - email
        - phone
        - createdAt
        - updatedAt
